services:
  sound-api-service:
    build:
        context: .
        dockerfile: ./Sound.Api/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80 
        - ASPNETCORE_Kestrel__Certificates__Default__Password=qwerty12345
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
        - ~/.aspnet/https:/https:ro
    ports:
    - 5000:443
    - 5001:80